#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER {{DB_NAME}} WITH PASSWORD 'secret';
    CREATE DATABASE {{DB_NAME}} OWNER {{DB_NAME}};
    GRANT ALL PRIVILEGES ON DATABASE {{DB_NAME}} TO {{DB_NAME}};
EOSQL
